/*
 * Name: server.rs
 * Purpose: Local HTTP REST API server for external automation.
 * Description: Binds to 127.0.0.1:8484 (localhost only). Opens its own
 *   read-only SQLite connection to avoid contending with the main
 *   app's Mutex. WAL mode enables concurrent readers. Runs in a
 *   background thread.
 * Tech Stack: Rust, tiny_http, serde_json
 * License: MIT
 * Authors: Amey Thakur (https://github.com/Amey-Thakur)
 *          Archit Konde (https://github.com/Archit-Konde)
 * Date: 2026-07-12
 */

use std::path::PathBuf;
use std::thread;

use rusqlite::Connection;
use tiny_http::{Header, Method, Response, Server};

use crate::database::repository::{
    chunk_repository, document_repository, note_repository, notebook_repository,
};

const API_PORT: u16 = 8484;
const CONTENT_TYPE_JSON: &str = "application/json";

/// Start the REST API server in a background thread.
/// Opens its own read-only database connection (WAL mode allows concurrent readers).
/// The session token is generated by AppState so the get_api_token command
/// and this server always agree on the credential.
pub fn start_api_server(db_path: PathBuf, api_token: String) {
    thread::spawn(move || {
        let expected_auth = format!("Bearer {}", api_token);
        let conn = match Connection::open_with_flags(
            &db_path,
            rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY | rusqlite::OpenFlags::SQLITE_OPEN_NO_MUTEX,
        ) {
            Ok(c) => c,
            Err(e) => {
                tracing::warn!("REST API: could not open database: {e}");
                return;
            }
        };

        /* WAL lets this reader run alongside the app's writer, but a checkpoint
        still takes a lock the reader has to wait behind. The default timeout is
        zero, which turns that brief overlap into an immediate "database is
        locked" and a failed request. The writer already waits five seconds; a
        reader that gives up sooner than the writer has no reason to. */
        if let Err(e) = conn.execute_batch("PRAGMA busy_timeout = 5000;") {
            tracing::warn!("REST API: could not set busy timeout: {e}");
        }

        let addr = format!("127.0.0.1:{API_PORT}");
        let server = match Server::http(&addr) {
            Ok(s) => {
                tracing::info!("REST API server running at http://{addr}");
                s
            }
            Err(e) => {
                tracing::warn!("Could not start REST API server: {e}");
                return;
            }
        };

        for request in server.incoming_requests() {
            let path = request.url().split('?').next().unwrap_or("/");
            if requires_auth(path) {
                let auth_ok = request.headers().iter().any(|h| {
                    /* HTTP header names are case-insensitive (RFC 7230), and
                    HTTP/2 and the fetch API send them lowercased, so match the
                    field name case-insensitively rather than exactly. */
                    h.field
                        .as_str()
                        .as_str()
                        .eq_ignore_ascii_case("authorization")
                        && constant_time_eq(h.value.as_str().as_bytes(), expected_auth.as_bytes())
                });
                if !auth_ok {
                    let header = Header::from_bytes("Content-Type", CONTENT_TYPE_JSON).unwrap();
                    let body = serde_json::json!({"error": "Unauthorized"}).to_string();
                    let r = Response::from_string(body)
                        .with_status_code(401)
                        .with_header(header);
                    request.respond(r).ok();
                    continue;
                }
            }

            let response = handle_request(&request, &conn);

            let header = Header::from_bytes("Content-Type", CONTENT_TYPE_JSON).unwrap();

            match response {
                Ok(body) => {
                    let r = Response::from_string(body).with_header(header);
                    request.respond(r).ok();
                }
                Err((status, msg)) => {
                    let error_json = serde_json::json!({ "error": msg }).to_string();
                    let r = Response::from_string(error_json)
                        .with_status_code(status)
                        .with_header(header);
                    request.respond(r).ok();
                }
            }
        }
    });
}

/// Whether a path needs the bearer token.
///
/// Everything does, except the exact health check, which exists so a caller can
/// discover the port and confirm the app is up without holding a credential.
///
/// Written as "everything except" rather than as a list of protected routes, so
/// a route added later is private by default. The opposite shape is how endpoints
/// end up public by omission.
fn requires_auth(path: &str) -> bool {
    path != HEALTH_PATH
}

/// The one public route.
const HEALTH_PATH: &str = "/api/health";

/// Compare two byte strings in constant time to avoid leaking the token
/// length-prefix through response timing. Local-only, but cheap to do right.
fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff: u8 = 0;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

fn handle_request(
    request: &tiny_http::Request,
    conn: &Connection,
) -> Result<String, (u16, String)> {
    let path = request.url().split('?').next().unwrap_or("/");
    let method = request.method();

    /* Repository errors are internal (500); unknown routes are 404 */
    let internal = |e: crate::error::AppError| (500u16, e.to_string());
    let encode = |e: serde_json::Error| (500u16, e.to_string());

    match (method, path) {
        (&Method::Get, p) if p == HEALTH_PATH => Ok(serde_json::json!({
            "status": "ok",
            "version": env!("CARGO_PKG_VERSION"),
            "api_port": API_PORT
        })
        .to_string()),

        (&Method::Get, "/api/notebooks") => {
            let notebooks = notebook_repository::list_all(conn).map_err(internal)?;
            serde_json::to_string(&notebooks).map_err(encode)
        }

        (&Method::Get, p) if p.starts_with("/api/notebooks/") && p.ends_with("/notes") => {
            let notebook_id = p
                .strip_prefix("/api/notebooks/")
                .and_then(|s| s.strip_suffix("/notes"))
                .unwrap_or("");
            let notes = note_repository::list_by_notebook(conn, notebook_id).map_err(internal)?;
            serde_json::to_string(&notes).map_err(encode)
        }

        (&Method::Get, p) if p.starts_with("/api/notebooks/") && p.ends_with("/documents") => {
            let notebook_id = p
                .strip_prefix("/api/notebooks/")
                .and_then(|s| s.strip_suffix("/documents"))
                .unwrap_or("");
            let docs =
                document_repository::list_by_notebook(conn, notebook_id).map_err(internal)?;
            serde_json::to_string(&docs).map_err(encode)
        }

        (&Method::Get, p) if p.starts_with("/api/documents/") && p.ends_with("/chunks") => {
            let doc_id = p
                .strip_prefix("/api/documents/")
                .and_then(|s| s.strip_suffix("/chunks"))
                .unwrap_or("");
            let chunks = chunk_repository::get_by_document(conn, doc_id).map_err(internal)?;
            serde_json::to_string(&chunks).map_err(encode)
        }

        (&Method::Get, "/api/chunks/count") => {
            let count = chunk_repository::count_all(conn).map_err(internal)?;
            Ok(serde_json::json!({ "count": count }).to_string())
        }

        _ => Err((404, format!("Not found: {} {}", method, path))),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn only_the_health_check_is_public() {
        assert!(!requires_auth("/api/health"));
        for path in [
            "/api/notebooks",
            "/api/notebooks/abc/notes",
            "/api/notebooks/abc/documents",
            "/api/documents/abc/chunks",
            "/api/chunks/count",
            "/",
            "",
        ] {
            assert!(requires_auth(path), "{path} must require the token");
        }
    }

    #[test]
    fn a_path_that_merely_starts_with_health_still_needs_the_token() {
        /* A prefix check here would have made every one of these public. */
        for path in [
            "/api/healthy",
            "/api/health/notebooks",
            "/api/health/../notebooks",
            "/api/health2",
        ] {
            assert!(requires_auth(path), "{path} must require the token");
        }
    }

    #[test]
    fn the_health_path_is_matched_exactly() {
        /* Case and trailing slash both fail closed, which is the safe way round:
        the worst outcome is that a caller has to send the token it already has. */
        assert!(requires_auth("/API/HEALTH"));
        assert!(requires_auth("/api/health/"));
        assert!(requires_auth(" /api/health"));
    }

    #[test]
    fn constant_time_eq_matches_only_identical_input() {
        assert!(constant_time_eq(b"Bearer abc", b"Bearer abc"));
        assert!(!constant_time_eq(b"Bearer abc", b"Bearer abd"));
        assert!(!constant_time_eq(b"Bearer abc", b"Bearer ab"));
        assert!(!constant_time_eq(b"", b"x"));
        assert!(constant_time_eq(b"", b""));
    }

    #[test]
    fn a_prefix_of_the_token_is_not_accepted() {
        /* The length check is what stops a truncated token matching; without it
        a caller could walk the token one byte at a time. */
        let real = b"Bearer nbl-api-0123456789abcdef";
        assert!(!constant_time_eq(b"Bearer nbl-api-", real));
        assert!(!constant_time_eq(real, b"Bearer nbl-api-"));
    }
}
